CREATE TABLE IF NOT EXISTS "user" (
	"user_id" integer PRIMARY KEY NOT NULL,
	"username" text NOT NULL UNIQUE COLLATE NOCASE,
	"pw_hash" text NOT NULL
);

CREATE TABLE IF NOT EXISTS "stats" (
	"stat" integer PRIMARY KEY NOT NULL,
	"str_bonus" integer NOT NULL,
	"dam_bonus" integer NOT NULL,
	"stat_bonus" integer NOT NULL,
	"carry" real NOT NULL
);

CREATE TABLE IF NOT EXISTS "saves" (
	"Save" text PRIMARY KEY NOT NULL,
	"lv1" integer NOT NULL,
	"lv2" integer NOT NULL,
	"lv3" integer NOT NULL,
	"lv4" integer NOT NULL,
	"lv5" integer NOT NULL,
	"lv6" integer NOT NULL,
	"lv7" integer NOT NULL,
	"lv8" integer NOT NULL,
	"lv9" integer NOT NULL,
	"lv10" integer NOT NULL,
	"lv11" integer NOT NULL,
	"lv12" integer NOT NULL,
	"lv13" integer NOT NULL,
	"lv14" integer NOT NULL,
	"lv15" integer NOT NULL,
	"lv16" integer NOT NULL,
	"lv17" integer NOT NULL,
	"lv18" integer NOT NULL,
	"lv19" integer NOT NULL,
	"lv20" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "Skills" (
	"Skill" text PRIMARY KEY NOT NULL,
	"Type" text NOT NULL,
	"Stat" text NOT NULL
);

CREATE TABLE IF NOT EXISTS "characters" (
	"id" integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	"user_id" integer,
	"name" text NOT NULL,
	"alignment_lc" text NOT NULL,
	"alignment_ge" text NOT NULL,
	"race" text NOT NULL,
	"cha_class" text NOT NULL,
	"level" integer NOT NULL,
	"strength" integer NOT NULL,
	"dexterity" integer NOT NULL,
	"constitution" integer NOT NULL,
	"intelligence" integer NOT NULL,
	"wisdom" integer NOT NULL,
	"charisma" integer NOT NULL,
	"honour" integer NOT NULL,
	"status" text NOT NULL,
	"height" integer NOT NULL,
	"weight" integer NOT NULL,
	"handedness" text NOT NULL,
	"eye_colour" text NOT NULL,
	"hair_colour" text NOT NULL,
	"sex" text NOT NULL,
	"age" integer NOT NULL,
	"acrobatics" INTEGER,
	"anatomy" INTEGER,
	"animal_lore" INTEGER,
	"appraisal" INTEGER,
	"arcana" INTEGER,
	"blacksmithing" INTEGER,
	"botany_forestry" INTEGER,
	"common" INTEGER,
	"culture" INTEGER,
	"dancing" INTEGER,
	"dwarven" INTEGER,
	"elvish" INTEGER,
	"engineering" INTEGER,
	"agriculture" INTEGER,
	"first_aid" INTEGER,
	"gnomish" INTEGER,
	"halfling" INTEGER,
	"history" INTEGER,
	"jeweler" INTEGER,
	"leather_working" INTEGER,
	"manual_labour" INTEGER,
	"masonry" INTEGER,
	"mathematics" INTEGER,
	"metal_working" INTEGER,
	"musical_ability" INTEGER,
	"observation" INTEGER,
	"religion" INTEGER,
	"sailing" INTEGER,
	"sleight" INTEGER,
	"sneak" INTEGER,
	"social_interaction" INTEGER,
	"tailoring" INTEGER,
	"tracking" INTEGER,
	"upkeep_maintenance" INTEGER,
	"woodworking" INTEGER,
	"experience" INTEGER NOT NULL,
	"commerce" integer NOT NULL
);
